import java.awt.Color;

public class TicTac extends javax.swing.JFrame {

byte value=0;
    public TicTac() {
        initComponents();
        this.setLocation(500,250);
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setTitle("Hiresh's TicTac");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b11 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        jtextfield = new javax.swing.JTextField();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b11.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b21.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });

        b31.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });

        b12.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b22.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });

        b13.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b32.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });

        b23.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });

        b33.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33ActionPerformed(evt);
            }
        });

        jtextfield.setText("Match ongoing..");

        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtextfield)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(b31, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b33, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b33, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(18, 18, 18)
                .addComponent(jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void check(){
    if(b11.getText().equals(b12.getText())&&b12.getText()==b13.getText()&&!"".equals(b11.getText())){
        jtextfield.setText(" "+b11.getText()+" Won the last match");
jtextfield.setBackground(Color.green);
        b11.setText("");
b12.setText("");
b13.setText("");
b21.setText("");
b22.setText("");
b23.setText("");
b31.setText("");
b32.setText("");
b33.setText("");
value=0;
}
    if(b21.getText().equals(b22.getText())&&b22.getText()==b23.getText()&&!"".equals(b21.getText())){
        jtextfield.setText(" "+b21.getText()+" Won the last match");
jtextfield.setBackground(Color.green);       
        b11.setText("");
b12.setText("");
b13.setText("");
b21.setText("");
b22.setText("");
b23.setText("");
b31.setText("");
b32.setText("");
b33.setText("");
value=0;
}
    if(b31.getText().equals(b32.getText())&&b32.getText()==b33.getText()&&!"".equals(b31.getText())){
        jtextfield.setText(" "+b31.getText()+" Won the last match");
        jtextfield.setBackground(Color.green);
        b11.setText("");
b12.setText("");
b13.setText("");
b21.setText("");
b22.setText("");
b23.setText("");
b31.setText("");
b32.setText("");
b33.setText("");
value=0;
}
    if(b11.getText().equals(b21.getText())&&b21.getText()==b31.getText()&&!"".equals(b11.getText())){
        jtextfield.setText(" "+b11.getText()+" Won the last match");
        b11.setText("");
        jtextfield.setBackground(Color.green);
b12.setText("");
b13.setText("");
b21.setText("");
b22.setText("");
b23.setText("");
b31.setText("");
b32.setText("");
b33.setText("");
value=0;
}
    if(b12.getText().equals(b22.getText())&&b22.getText()==b32.getText()&&!"".equals(b12.getText())){
        jtextfield.setText(" "+b12.getText()+" Won the last match");
        jtextfield.setBackground(Color.green);
        b11.setText("");
b12.setText("");
b13.setText("");
b21.setText("");
b22.setText("");
b23.setText("");
b31.setText("");
b32.setText("");
b33.setText("");
value=0;
}
    if(b13.getText().equals(b23.getText())&&b23.getText()==b33.getText()&&!"".equals(b13.getText())){
        jtextfield.setText(" "+b13.getText()+" Won the last match");
jtextfield.setBackground(Color.green);
        b11.setText("");
b12.setText("");
b13.setText("");
b21.setText("");
b22.setText("");
b23.setText("");
b31.setText("");
b32.setText("");
b33.setText("");
value=0;
}
    if(b11.getText().equals(b22.getText())&&b22.getText()==b33.getText()&&!"".equals(b11.getText())){
        jtextfield.setText(" "+b22.getText()+" Won the last match");
        jtextfield.setBackground(Color.green);
        b11.setText("");
b12.setText("");
b13.setText("");
b21.setText("");
b22.setText("");
b23.setText("");
b31.setText("");
b32.setText("");
b33.setText("");
value=0;
}
    if(b13.getText().equals(b22.getText())&&b22.getText()==b31.getText()&&!"".equals(b13.getText())){
        jtextfield.setText(" "+b22.getText()+" Won the last match");
        jtextfield.setBackground(Color.green);
        b11.setText("");
b12.setText("");
b13.setText("");
b21.setText("");
b22.setText("");
b23.setText("");
b31.setText("");
b32.setText("");
b33.setText("");
value=0;
}
}
    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
    value++;
    if(value%2==1){
        b11.setText("X");
    }
    if(value%2==0){
        b11.setText("O");
    }
    check();
    }//GEN-LAST:event_b11ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
value++;
    if(value%2==1){
        b21.setText("X");
    }
    if(value%2==0){
        b21.setText("O");
    }
    check();        // TODO add your handling code here:
    }//GEN-LAST:event_b21ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
value++;
    if(value%2==1){
        b31.setText("X");
    }
    if(value%2==0){
        b31.setText("O");
    }
    check();        // TODO add your handling code here:
    }//GEN-LAST:event_b31ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
value++;
    if(value%2==1){
        b12.setText("X");
    }
    if(value%2==0){
        b12.setText("O");
    }
    check();        // TODO add your handling code here:
    }//GEN-LAST:event_b12ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
value++;
    if(value%2==1){
        b22.setText("X");
    }
    if(value%2==0){
        b22.setText("O");
    }
    check();        // TODO add your handling code here:
    }//GEN-LAST:event_b22ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
value++;
    if(value%2==1){
        b13.setText("X");
    }
    if(value%2==0){
        b13.setText("O");
    }
    check();        // TODO add your handling code here:
    }//GEN-LAST:event_b13ActionPerformed

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
value++;
    if(value%2==1){
        b32.setText("X");
    }
    if(value%2==0){
        b32.setText("O");
    }
    check();        // TODO add your handling code here:
    }//GEN-LAST:event_b32ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
value++;
    if(value%2==1){
        b23.setText("X");
    }
    if(value%2==0){
        b23.setText("O");
    }
    check();        // TODO add your handling code here:
    }//GEN-LAST:event_b23ActionPerformed

    private void b33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33ActionPerformed
value++;
    if(value%2==1){
        b33.setText("X");
    }
    if(value%2==0){
        b33.setText("O");
    }
    check();        // TODO add your handling code here:
    }//GEN-LAST:event_b33ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
b11.setText("");
b12.setText("");
b13.setText("");
b21.setText("");
b22.setText("");
b23.setText("");
b31.setText("");
b32.setText("");
b33.setText("");
value=0;
jtextfield.setText("Match is considered Draw");
jtextfield.setBackground(Color.red);

    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton clear;
    private javax.swing.JTextField jtextfield;
    // End of variables declaration//GEN-END:variables
}
